### ISSUE TITLE
new release?

### ISSUE THREAD

**Issue by mweastwood** [ajkeller34/Unitful.jl#100]
Can I pester you to tag a new release? I'd like to set the next release as the lower bound for UnitfulAstro.

**Comment by ajkeller34** [comment]
Done. https://github.com/JuliaLang/METADATA.jl/pull/11276

**Comment by mweastwood** [comment]
Gotta love attobot. Thanks!

**Comment by ajkeller34** [comment]
Ah, scratch that, it has to be 0.3.0. I'll retag as 0.3.0. The next version is going to have to be 0.4.0 then, because I'm adding logarithmic quantity support sometime this week ideally.

**Comment by ajkeller34** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/11278
