### ISSUE TITLE
[Feature] Dimensionful/Heterogeneous Matrices?

### ISSUE THREAD

**Issue by NOTtheMessiah** [ajkeller34/Unitful.jl#11]
Useful in general relativity. As described in this blog post: http://blog.sigfpe.com/2016/08/dimensionful-matrices.html

These seem like they would be different from Array{Any}. Unable to check if any of this is currently possible as I am not running Julia v0.5.

**Comment by ajkeller34** [comment]
This is an intriguing idea. I have no immediate need for this functionality myself, but I'd be happy to consider pull requests if you want to try implementing it. I don't know how far you would get with just `Array{Any}` but you would almost certainly want to make a new array type to do this efficiently.

I've rewritten some of this package to enable dispatch on dimensions (i.e. `f(x::Length)`) so you might want to check out the "rewrite" branch of this repo if you do decide to play around with Julia v0.5. Release candidates are out, FWIW. I plan on releasing and tagging not too long after 0.5 is officially released.

**Comment by ajkeller34** [comment]
I've enabled this functionality in the `rewrite` branch of this repo. The standard `Array` type is used, specializing on an `AbstractQuantity{T}` type. If all goes well I intend to roll this out once Julia 0.5 is released. You should be aware that this branch is currently broken on 0.5-rc3, but does work on 0.5-rc1 and 0.5-rc2. I'm not sure what's going on but hopefully it is a temporary bug in 0.5-rc3.

Here's an example.
```
julia> using Unitful
INFO: Recompiling stale cache file /Users/ajkeller/.julia/lib/v0.5/Unitful.ji for module Unitful.

julia> @unit c "c" SpeedOfLight 299792458u"m/s" false
c

julia> uconvert(u"m/s", 1c)
299792458//1 m s^-1

julia> [-1.0c^2 0 0 0; 0 1 0 0; 0 0 1 0; 0 0 0 1]
4×4 Array{Unitful.AbstractQuantity{Float64},2}:
 -1.0 c^2  0.0  0.0  0.0
      0.0  1.0  0.0  0.0
      0.0  0.0  1.0  0.0
      0.0  0.0  0.0  1.0

julia> versioninfo()
Julia Version 0.5.0-rc2+0
Commit 0350e57 (2016-08-12 11:25 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.7.1 (ORCJIT, haswell)
```

**Comment by ajkeller34** [comment]
The kind of functionality you are discussing is now possible in the master branch of this package. However, because the array will not be of concrete type (you get `Array{Number}`), performance may not be so great. The only way around this would be to make a new kind of quantity where the units are encoded as a value, not in the type signature. At least in this case you could store such quantities efficiently in an concretely typed array, although performance would still take a hit because the unit math would happen at run time.
