### ISSUE TITLE
eps(T) should return a dimensionless quantity

### ISSUE THREAD

**Issue by stevengj** [ajkeller34/Unitful.jl#121]
For `x::T` where `T<:Quantity`, the return value of `eps(x)` should have the same type `T`, but the return value of `eps(T)` should have the type of `one(T)`.  Currently, that isn't the case:

```
julia> eps(x)
2.220446049250313e-16 m

julia> eps(typeof(x))      #  should give a Float64
2.220446049250313e-16 m
```

Equivalently, `eps(T)` should be a *relative*  precision, i.e. it should be dimensionless.  (e.g. it is used for relative tolerances in `isapprox` and elsewhere).

**Comment by stevengj** [comment]
The fix is trivial: just remove the `T(...)` from [this line](https://github.com/ajkeller34/Unitful.jl/blob/2981c37cada5eec02e1a224e7e526a3d6dbcd319/src/quantities.jl#L273).

**Comment by ajkeller34** [comment]
Ah, I wasn't aware of that. Thanks! Closed by a76397c75dcfa59d8328ab60effb55a9ad4d0c6a

**Comment by PatrickHaecker** [comment]
Is this really the right fix? I just wanted to open an issue due to the inconsistent behavior which was a result of this "fix":

```julia
import Unitful: m, 𝐋, Quantity
```
```julia
julia> typemax(0m)
9223372036854775807 m
```
```julia
julia> typemax(Quantity{Float16, 𝐋, m |> typeof})
Inf16 m
```
```julia
julia> eps(Float16(0)m)
Float16(6.0e-8) m
```
```julia
eps(Quantity{Float16, 𝐋, m |> typeof})
Float16(0.000977)
```
```julia
julia> using Dates; eps(DateTime)
1 millisecond
```

In other words, all agree, that `eps(::Type{T})` should have a dimension like e.g. `typemax(::Type{T})` until this was changed here.
I do not understand what the advantage of `eps((::Type{T}))` being dimensionless should be, but if this fix is really correct, then in my understanding Base is wrong (at least the whole Dates package).

**Comment by stevengj** [comment]
`eps` is a *relative* precision.  It is meaningless to give it a unit.   The fact that it is a relative precision is at the heart of all floating-point arithmetic.   It's totally different from `typemax`.

It's very different from `eps(x::T)`, which is an *absolute* (not relative) precision the value of `x`.  That's why `eps(x::T)` is dimensionful but `eps(::Type{T})` is dimensionless.

**Comment by PatrickHaecker** [comment]
Thanks a lot for the explanation, I think I got it. I know this is not the right place, but I think the documentation of `eps` would benefit from your nuanced explanation about fixed-point types and floating-point types before going into the floating-point specifics.  

But doesn't that mean that whether `eps::Type{T}` has a unit or not should depend on whether `T` is a floating point value or not?
Interestingly, that was the very use case where I stumbled about this:
```julia
import Unitful: m, 𝐋, Quantity
using FixedPointNumbers
eps(Quantity{Fixed{Int8,2}, 𝐋, m |> typeof})
0.25Q5f2
```
Analogous to `DateTime`, this should be dimensionful. So this would be testing against `AbstractFloat` when deciding to print the unit, wouldn't it?

**Comment by stevengj** [comment]
This is definitely not the right place for it, but I agree it's a bit unfortunate that `eps` is used for both relative and absolute precisions.

**Comment by PatrickHaecker** [comment]
Getting back from the general discussion to `Unitful` and keeping the difference between `eps(x::T)` and `eps::Type{T}` aside:
Currently `eps::Type{T}` should return a unit when it's a fixed point number (see above explanation or e.g. `Dates`). However, `Unitful` does never show a unit. I propose to change `Unitful` to only hide the number if `T` is a subtype of `AbstractFloat`. If I counted correctly, that would be 4 occurrences in `quantities.jl`.

Is this a plausible way forward? If we have agreement, I'd prepare a PR.
