### ISSUE TITLE
(breaking) Change day's variable from `d` to `dy`

### ISSUE THREAD

**Issue by yakir12** [ajkeller34/Unitful.jl#122]
The usage of `d` as a variable indicating other things than days is not uncommon and therefore results in a clash when we `import Unitful:d`. I solve this by `const dy=u"d"`, but I bet I'm not alone. This strikes me as a really simple small change that would improve on this mini issue tremendously, especially before we get to Julia's v1.0.
So, would you be interested in a PR that replaces all the `d` days to `dy` days?

**Comment by ajkeller34** [comment]
I don't really see this as an issue, in fact there are already two solutions:

1) Use the unit string macro.
2) Take advantage of module-scoped namespaces by doing what you're already doing.

I'm not so sure what's special about `d` when there are so many other short symbols defined.

**Comment by yakir12** [comment]
I can see what you mean by a lot of other one-letter symbol, but:
1. While I agree that `d` is an acceptable abbreviation for day, it's not as "common knowledge" as `m` is for Meter, so it's not like there is some necessity to specifically stick to `d`. 
2. You already (almost) have a two letter "convention" for those time periods: 

```julia
@unit minute "minute" Minute 60s     false
@unit hr     "hr"     Hour   3600s   false
@unit d      "dy"     Day    86400s  false
@unit wk     "wk"     Week   604800s false
```

But I totally accept if you can't be bothered, this is hardly worth the time it's already taking.
