### ISSUE TITLE
Specific kinds of mols

### ISSUE THREAD

**Issue by rafaqz** [ajkeller34/Unitful.jl#124]
I'm just adding Unitful.jl to a few biophysical packages I'm writing where most of the units are some flavour of mol or mol A / mol B. So I though I would comment while I have the idea. I still don't have much experience with Unitful.jl, and it may not be at all useful or helpful in practise.

It would be great to be able to specify the _kind_ of mol, something like:
```
1u"mol(N)"
1u"mol(CO2)" 
1u"mol(Quanta)" # photon irradiance
0.1u"mol(N)/mol(C)"
```

Currently:
```
julia> 2u"mol/mol"
2
```

But with this proposal:
```
julia> 2u"mol(N)/mol(C)"
2 mol(N) mol(C)-1
```

These could be defined add-hoc, but a simple api could allow defining the kind of mol in a regular reusable way. It could also facilitate specifying the molar mass for conversions to g.

This could be a separate package or a pull request, but any thoughts would be helpful before I look into that further.

**Comment by ajkeller34** [comment]
I'd suggest playing around with following examples, then let me know what you think needs improvement:

```
help?> @unit

  @unit(symb,abbr,name,equals,tf)

  Define a unit. Rather than specifying a dimension like in @refunit, equals should be a Unitful.Quantity equal to one
  of the unit being defined. If tf == true, symbols will be made for each power-of-ten prefix.

  Returns the Unitful.FreeUnits object to which symb is bound.

  Usage example: @unit mi "mi" Mile (201168//125)*m false

  This example will not generate kmi (kilomiles).

julia> 

julia> @unit molN "mol(N)" MolesN 1u"mol" false
mol(N)

julia> molNfix = Unitful.FixedUnits(molN)
mol(N)

julia> @unit molCO2 "mol(CO2)" MolesCO2 1u"mol" false
mol(CO2)

julia> molCO2fix = Unitful.FixedUnits(molCO2)
mol(CO2)

julia> 1molN + 1molN
2 mol(N)

julia> 1molCO2 + 1molCO2
2 mol(CO2)

julia> 1molCO2 + 1molN
2//1 mol

julia> 1molCO2fix + 1molNfix
ERROR: automatic conversion prohibited.
[...]

julia> 1molCO2fix + 1molCO2fix
2 mol(CO2)
```

**Comment by rafaqz** [comment]
That's amazing. Maybe a macro could wrap that up?

```
julia> @mol N
julia> @mol C
julia>1molN/molC
1 molC molN^-1   
```

As in the @mol N macro output something like:
```
 @unit _molN "mol(N)" MolesN 1u"mol" false
 molN = Unitful.FixedUnits(_molN)
```

Not sure how easy this is but this would also be great:
```
julia>@mol C 12.0107
julia>uconvert(u"g", 10molC)
120.107g
```

**Comment by mol** [comment]
There's only one @mol - me :)

**Comment by mol** [comment]
Hehe, that's alright :)

**Comment by rafaqz** [comment]
I'm thinking that defining mols as u"g" may be the way to go. Does this make sense?

```
 @unit _molN "molN" MolesN 14.0067u"g" false
molN = Unitful.FixedUnits(_molN)

julia> uconvert(u"g", 5molN)                                                        
70.0335 g
```

I'll write a `@mol` macro to abstract that away to have an `@mol N 14.0067 ` syntax, when I have some time in the next few weeks. 

Maybe a tiny Moles.jl package? It could have that macro and maybe optionally definitions of the elements and common compounds so they can be standardised for everyone, unless you prefer a pull request here. Let me know what you think of the syntax and the general idea.

**Comment by rafaqz** [comment]
Done. Predefined mol units are in a separate package to the macro, in case people want to use more accurate values, or specific isotope concentrations.

https://github.com/rafaqz/UnitfulMoles.jl
https://github.com/rafaqz/UnitfulConventionalMoles.jl

**Comment by rafaqz** [comment]
`@compound H 2 0` should also be possible, getting weight for free from mol units already defined.

I'm just wondering how to get hold of the weight values inside the compound macro, so that either user defined or module defined mol units are available.

**Comment by rafaqz** [comment]
`@compound H 2 O` works now too, so I'll close this. Thanks for the help getting started.
