### ISSUE TITLE
Ability to describe groups of units?

### ISSUE THREAD

**Issue by rofinn** [ajkeller34/Unitful.jl#126]
It would be nice for dispatch purposes if we could summarize a collection of units. For example, we could have `f(input::P, output::P) where P<:Power` and this function could handle any kind of power related unit (e.g., `W`, `kW`, `MW`).

**Comment by ajkeller34** [comment]
Here are a few silly examples

```
julia> f(input::Unitful.PowerUnits, output::Unitful.PowerUnits) = "power"
f (generic function with 1 method)

julia> f(u"mW", u"kW")
"power"
```

```
julia> f(input::Unitful.Power, output::Unitful.Power) = input
f (generic function with 2 methods)

julia> f(3u"mW", 5u"kW")
3 mW
```

**Comment by rofinn** [comment]
Wow, magic :) Oh, so that's what `@derived_dimension` is for?

**Comment by rofinn** [comment]
Okay, thanks. Looks like I just didn't know how to use `@derived_dimension` properly.
