### ISSUE TITLE
one() and zero() are inconsistent

### ISSUE THREAD

**Issue by rafaqz** [ajkeller34/Unitful.jl#134]
I'm just wondering why one(x) returns a unitless value while zero(x) returns a unitful quantity? It's no big deal but it's not what I expected, when one(x) and zero(x) normally return the same type.

```
zero(x::Quantity) = Quantity(zero(x.val), unit(x))
zero(x::Type{Quantity{T,D,U}}) where {T,D,U} = zero(T)*U()

one(x::Quantity) = one(x.val)
one(x::Type{Quantity{T,D,U}}) where {T,D,U} = one(T)
```

**Comment by ajkeller34** [comment]
`one` is the multiplicative identity, `oneunit` is the additive group generator.

**Comment by rafaqz** [comment]
Thanks. That is the most I've learned from 11 words this year.
