### ISSUE TITLE
hbar has wrong units.

### ISSUE THREAD

**Issue by MasonProtter** [ajkeller34/Unitful.jl#135]
I was (perhaps erroneously) working under the assumption that `hbar` in Unitful was reduced Plank's constant but that appears to be false. Instead, I get
```
julia> dimension(1u"hbar")
𝐋^-1 𝐌 𝐓^-2
```
which is off by a power of length cubed. Is `1u"hbar"` something other than what I thought?

**Comment by ajkeller34** [comment]
Hectobars... an unfortunate consequence of supporting most SI prefixes. You can type `\hbar <tab>` in the REPL to autocomplete `ħ`.
