### ISSUE TITLE
Base units not exported?

### ISSUE THREAD

**Issue by barche** [ajkeller34/Unitful.jl#14]
Hi,

Unless I'm missing something, base units like `m` and `kg` are not available after upgrading to the latest master. I wiped the old version and did

```
Pkg.clone("https://github.com/ajkeller34/Unitful.jl.git")
Pkg.build("Unitful")
using Unitful
```

After that, I get e.g. `ERROR: UndefVarError: kg not defined`. This on Julia 0.5-rc3.

**Comment by ajkeller34** [comment]
Units are no longer exported, as stated in the manual.  It's simply too easy to overwrite units and fundamental constants if they are exported. Consider that `c` is the speed of light, `a` is an are (related to the hectare), etc. 

You have a few options:

1) You can explicitly import them, perhaps in .juliarc if you know you always want this behavior at the REPL, although I haven't played around with .juliarc too much myself.

2) You can use a string macro: `u"m"` or `u"kg"` in place of `m` or `kg`. You are encouraged to do multiplication, division, exponentiation of units inside the macro: `u"kg*m/s^2"`.

**Comment by ajkeller34** [comment]
Thanks also for the kind words regarding the package on the mailing list! I hope it is useful to you!

**Comment by barche** [comment]
Ah, sorry, completely missed that, working perfectly now, thanks.
