### ISSUE TITLE
Dimensions and terminal fonts

### ISSUE THREAD

**Issue by rafaqz** [ajkeller34/Unitful.jl#147]
It's great to have a shorter show format. Unfortunately the dimensions symbols used don't print in a lot of terminals or terminal fonts! 𝐌 etc just show as a square,  even with extra fonts like Symbola as fallbacks.

It probably works fine in atom, by I always end up back in raw vim and a terminal to do 'real' coding work, and I guess some minor percentage of other users do as well. Edit: its just the spacing, not the font ~~I scanned through a lot of available coding fonts but the majority don't support all of the symbols used, especially the two-character symbols.~~ Maybe my font config could be better, but linux font config is one hell I try to avoid!

**Comment by rafaqz** [comment]
Solved - setting a very wide font spacing lets most of the dimension characters print, although 𝐌 persistently prints as a square box no matter how wide I set it.

Maybe worthy of mention in the docs somewhere, it looks really bad without a fix.

**Comment by ajkeller34** [comment]
As much as I like the shorter show format I don't think we can keep it anyway. It is implicated in one of the two failures in #148 so it will be removed in the next commit. I'd welcome a PR to the docs about getting those characters to display correctly in other contexts though.

**Comment by MartinOtter** [comment]
How to set a wide font spacing in an editor (on Windows 10). I am using Notepad++ and Visual Studio Code. In none of these editors, I found an option to set "wide font spacing".

**Comment by rafaqz** [comment]
I use urxvt on linux so I can't really help sorry. The advice may also not apply in those contexts.

**Comment by MartinOtter** [comment]
Which font family are you using (maybe this font is availabe on Windows 10)

**Comment by MartinOtter** [comment]
I tried the font "DejaVuSansMono" (has support for a lot of symbols), but it did not help. Any other suggestion for a font?
