### ISSUE TITLE
Document @unit __init__ gymnastics

### ISSUE THREAD

**Issue by cstjean** [ajkeller34/Unitful.jl#174]
It took me some time to figure out this trick from UnitfulUS:

```julia
# Some gymnastics required here because if we precompile, we cannot add to
# Unitful.basefactors at compile time and expect the changes to persist to runtime.
const localunits = Unitful.basefactors
function __init__()
    merge!(Unitful.basefactors, localunits)
    Unitful.register(UnitfulUS)
end
```

It should perhaps be [documented](http://ajkeller34.github.io/Unitful.jl/stable/newunits/)?

**Comment by ajkeller34** [comment]
It is documented, but the documentation is in a [non-obvious spot](http://ajkeller34.github.io/Unitful.jl/stable/extending/). How about I merge this section into the section you linked to?

**Comment by cstjean** [comment]
Sure, or maybe it's simpler to add a link to the other page.
