### ISSUE TITLE
d for day?

### ISSUE THREAD

**Issue by cstjean** [ajkeller34/Unitful.jl#175]
Currently, `@unit d "dy" Day 86400s false`. Was that intentional? It's a bit odd that 

```julia
julia> u"d"
dy
```

**Comment by cstjean** [comment]
I see this was discussed in https://github.com/ajkeller34/Unitful.jl/issues/122. I don't have a preference between `d` and `dy`; I just find it weird that its printed representation and `u` input is different.

**Comment by ajkeller34** [comment]
I'd prefer `d` since that is the widely accepted symbol. If I had reasoning for displaying it differently I don't remember what it was.
