### ISSUE TITLE
oneunit(1u"°C") is not defined

### ISSUE THREAD

**Issue by cstjean** [ajkeller34/Unitful.jl#181]
Should it not be `1K`?

**Comment by ajkeller34** [comment]
This would go even more explicitly against the docstring, but I suppose it is in the spirit of defining `zero`.

**Comment by cstjean** [comment]
Ah, that's true. Perhaps there should be a conversation about these issues in Base? I already have a PR, I'll submit it, but it's not critical for my code; just something I accidentally depended on.

**Comment by ajkeller34** [comment]
Happy to merge your PR. I think the only way we'll have the answer for what works best is by trying the code in real world applications, since the docs are a little underspecified about what these functions should do when the types in question don't behave exactly like additive groups.
