### ISSUE TITLE
Tag?

### ISSUE THREAD

**Issue by nicoleepp** [ajkeller34/Unitful.jl#192]
Wondering if a new version could be tagged  to avoid precompilation warnings in other packages running into https://github.com/ajkeller34/Unitful.jl/issues/133

**Comment by ajkeller34** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/19557

**Comment by ajkeller34** [comment]
A change to the type signature of `Quantity` is causing a few packages to fail tests. I'm submitting some PRs to those packages to upper-bound the Unitful version.

**Comment by nicoleepp** [comment]
Thank you :)
