### ISSUE TITLE
typeof(1.0u"m") <: Number is true, typeof(1.0u"m") <: Real is false, but should be true

### ISSUE THREAD

**Issue by zappotek** [ajkeller34/Unitful.jl#197]
Hello all,
Just a small point,
let's say a variable has some concrete subtype of number
A unitful unit attatched to this variable should also be considered a subtype of all of it's original type's supertypes

i.e

```
>typeof(variable)
Subtype

>Subtype <: Number 
 true

>Subtype <: SupertypeOfSubtype
true

> typeof((variable)u"UnitfulUnit") <: SupertypeOfSubtype
true
```

**Comment by ajkeller34** [comment]
You've made no case for why that must be so, and in fact I disagree with the issue title. See https://github.com/ajkeller34/Unitful.jl/issues/9#issuecomment-236252304 for some prior discussion.
