### ISSUE TITLE
multiple granularities within a single physical dimension

### ISSUE THREAD

**Issue by JeffreySarnoff** [ajkeller34/Unitful.jl#2]
With the physical dimension of _Time, and the base relative unit, the unit of _Second,
we define _Minute and _Hour as exact integer multiples of the relative unit.
Adopting a coarser granularity, and granularity based relative unit, the unit of _Month,
we define _Year and _Century as exact integer multiples of the relative unit.

When the situation allows, we prefer to work with granularity based relative unit and
units of measure naturally expressible as exact scalars, relative to the relative unit.

This is distinct from support for multiple systems of units, yet its support, cleanly realized,
may be expressed sharing much of the approach that allows work with different unit systems
without forcing each unit system to be a facade laid over the expression of SI unit values.

Have you developed some design/implementation insight just well-suited?

**Comment by ajkeller34** [comment]
There's now support for respecting exact conversions and I don't think SI units are fundamental to the code base at this point. I hope this answers your question but if not please reopen the issue.

**Comment by djsegal** [comment]
@ajkeller34 is there any word on opening this again?

i think the following would be pretty useful:

+ `seconds`
+ `days`
+ `weeks`
+ `months`
+ `years`
