### ISSUE TITLE
Add a method to `in` for convenient unit conversion?

### ISSUE THREAD

**Issue by ajkeller34** [ajkeller34/Unitful.jl#20]
```
julia> import Base:in

julia> in(x::Quantity, y::Unitful.Units) = uconvert(y,x)
in (generic function with 28 methods)

julia> 3u"m"
3 m

julia> ans in u"cm"
300//1 cm
```

I'm not sure whether to encourage this sort of thing although it's awfully nice at the REPL.

**Comment by tbreloff** [comment]
I get why you'd like this, but I'm sure the julia-gods would not be happy.  Here's a couple ways I might translate `ans in u"cm"` without knowing any better:

- Is `ans` already in units of `cm`?
- Is `ans` a type that is compatible/convertible with `cm`?

I guess the point is that `in` is normally asking a question (boolean result) and it would be weird IMO to do a conversion instead.

Instead, what about:

```julia
julia> =>(x::Quantity, y::Unitful.Units) = uconvert(y,x)
Pair{A,B}

julia> 3u"m"
3 m

julia> ans => u"cm"
300//1 cm
```

**Comment by ajkeller34** [comment]
I agree `in` is probably bad to use (not only because of parsing ambiguities, but also because the function already has a defined meaning in Base, as you point out). Using `=>` is also problematic for certain dictionaries:

```
julia> =>(x::Quantity, y::Unitful.Units) = uconvert(y,x)
=> (generic function with 1 method)

julia> Dict((1u"m")=>u"m")
ERROR: ArgumentError: Dict(kv): kv needs to be an iterator of tuples or pairs
```

I wonder if something like the following might work:
```
julia> (y::Unitful.Units)(x::Quantity) = uconvert(y, x)

julia> 1u"m" |> u"cm"
100//1 cm
```

In this case I'm using `|>` correctly (function chaining) but it still has the appearance of a unit conversion operation.

**Comment by ajkeller34** [comment]
Also, since `Units` objects have no fields, this is totally unambiguous.
