### ISSUE TITLE
Reduce to base units?

### ISSUE THREAD

**Issue by ggggggggg** [ajkeller34/Unitful.jl#25]
Is there a function to reduce to base units?

I can do
```
julia> uconvert(u"m",4u"m^3"/2u"cm^2")
20000.0 m
```

But only if I already know it has units of meters, but what if I want to just get to base units without knowing what they will be?

**Comment by ajkeller34** [comment]
Can't be done yet, but sometimes the operation is done implicitly in promotion when arrays are created. I don't think it will be too hard to implement.

**Comment by ajkeller34** [comment]
This has been implemented on master with a function called `upreferred` that can be called on dimensions, units, or quantities. It will appear in v0.0.3 (along with documentation). This version has been tagged and is awaiting incorporation into METADATA.
