### ISSUE TITLE
failed uconvert example

### ISSUE THREAD

**Issue by ggggggggg** [ajkeller34/Unitful.jl#27]
Here is a surprising failed call to `uconvert`. It works to convert to `u"cm^-2"` but not to convert to `u"1/cm^2"`.

```julia
julia> 1u"1/cm^2"==1u"cm^-2"
true
julia> uconvert(u"cm^-2",1u"fs*W/(eV*cm^2)")
6241.509125883258 cm^-2
julia> uconvert(u"1/cm^2",1u"fs*W/(eV*cm^2)")
ERROR: MethodError: no method matching uconvert(::Unitful.Quantity{Int64,Unitful.Dimensions{(Unitful.Dimension{:Length}(-2//1),)},Unitful.Units{(Unitful.Unit{:Meter}(-2,-2//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(-2//1),)}}}, ::Unitful.Quantity{Int64,Unitful.Dimensions{(Unitful.Dimension{:Length}(-2//1),)},Unitful.Units{(Unitful.Unit{:Meter}(-2,-2//1),Unitful.Unit{:Second}(-15,1//1),Unitful.Unit{:Watt}(0,1//1),Unitful.Unit{:eV}(0,-1//1)),Unitful.Dimensions{(Unitful.Dimension{:Length}(-2//1),)}}})
Closest candidates are:
  uconvert{T,D,U}(::Unitful.Units{N,D}, ::Unitful.Quantity{T,D,U}) at /Users/oneilg/.julia/v0.5/Unitful/src/Conversion.jl:21
  uconvert(::Unitful.Units{N,D}, ::Number) at /Users/oneilg/.julia/v0.5/Unitful/src/Conversion.jl:58
```

**Comment by ajkeller34** [comment]
Probably this just means we should reconsider if numerals are allowed in `u_str`. The `1` is passing through, making it a quantity and not a unit, and `uconvert` (I think naturally) expects you to convert to a unit, not a quantity. Will reference in #23.

**Comment by ajkeller34** [comment]
I guess "passing through" is not quite correct; rather there is no check to see that the result will indeed be a unit and not a quantity.

**Comment by ggggggggg** [comment]
That makes sense. When I wrote `Physical.jl` (my attempt at units) I let the left argument of `as` (equivalent of `uconvert`) be a quantity, but it just ignored the value. I was never sure that this was a good idea or not, but it does solve this issue. Probably a better error message would be in order so that it was something like:
```julia
julia> uconvert(u"1/cm^2",1u"fs*W/(eV*cm^2)")
ERROR: UConvertError: The first argument to uconvert must be a Unitful.Unit, you passed a Quantity.
```
