### ISSUE TITLE
Tests which use Unitful have side-effects

### ISSUE THREAD

**Issue by ChrisRackauckas** [ajkeller34/Unitful.jl#42]
The first time I ran a code which used Unitful in the tests when it was not installed it was fine, but the second time I got:

``` julia
INFO: Building Unitful
WARNING: `Pkg.build("Unitful.jl")` was run, but /home/crackauc/.julia/v0.5/Unitful/deps/Defaults.jl already exists. No action has been taken. If you encounter problems, you might consider backing up then deleting the existing file at /home/crackauc/.julia/v0.5/Unitful/deps/Defaults.jl, then running `Pkg.build("Unitful")` again.
```

which means that Unitful leaves something behind when it's removed. I think this is related to #33? @tkelman might want to chime in.

**Comment by ajkeller34** [comment]
Not really sure why that would happen, unless files named in .gitignore are not cleaned up when packages are removed, or you installed something else that required Unitful between the two tests... Does the rest of the package get removed following the test?

**Comment by tkelman** [comment]
Pkg.rm does not actually delete packages, it moves them as is to a .trash folder.

**Comment by ajkeller34** [comment]
Fixed on master (see "latest" docs for info about the upcoming version 0.1.0).
