### ISSUE TITLE
Stripping of units

### ISSUE THREAD

**Issue by phlavenk** [ajkeller34/Unitful.jl#48]
Unitful is an amazing package and seems to me to be the one superseding all the others - I'd like to consider it (after some further maturity) to get part of the Julia "standard packages" ecosystem.
I'm used to the unit system of CLHEP library used in high-energy physics codes (e.g. [manual](http://cmd.inp.nsk.su/old/cmd2/manuals/cernlib/CLHEP/UserGuide/Units/units.html), [git](https://gitlab.cern.ch/CLHEP/CLHEP)), where the workflow is following:

At the input, all values are multiplied by the input unit, all computations are done with units and at the output (or binary interface or ccall to a library), the variable is divided by the desired unit:
```
u = 15u"V"
d = 5u"mm"
E = u/d
outE = E/u"V/m"
>3.0 mm^-1 m
```
I'd like outE v to be an unitless value of  3000.
This would be much more readable than having to write `upreferred(outE)`, or using convert and ustrip functionality. Compare the following easy readable code (as would be in CLHEP)
```
println("The field intensity is $(E/u"V/m") [V/m] in a gap of $(d/u"m") [m]")
>The field intensity is 3000.0 [V/m] in a gap of 0.005 [m]
```
with the current verbosity
```
println("The field intensity is $(ustrip(float(uconvert(u"V/m", E)))) [V/m] in a gap of $(ustrip(float(uconvert(u"m", d)))) [m]")
>The field intensity is 3000.0 [V/m] in a gap of 0.005 [m]
```
Is it possible to specialize somehow the `/` operator in such a way that if dimensions of both operands are same, the units are correctly stripped, giving just a float number?
At least for cases where just different unit multiples of the same basic unit are uses, such as `mm` and `m`, etc.
Thank you for the advice.

**Comment by phlavenk** [comment]
What about this implementation? Dispatches only if Quantity is divided by Unit and dimensions of both match. Return always Float64 for consistency, independent of unit multiplication factor.
Works also well for arrays, one has to use `./` e.g.: `[1u"s", 1u"ms"]./u"ns"`

```julia
"""
    /{T, D, UA,  UU}(a::Unitful.Quantity{T,D,UA}
Specialization of division by unit if both are of same dimensionality.

This allows simple code with conversion to unitles number.
#Example
***jldoctest
julia> u = 15u"V"; d = 5u"mm"; E = u/d
3.0 mm^-1 V
julia> println("The field intensity is $(E/u"V/m") [V/m] in a gap of $(d/u"m") [m]")
The field intensity is 3000.0 [V/m] in a gap of 0.005 [m]
***

#Tests (TODO: add this into tests)
 @test typeof(1.0u"kg*m"/u"mm")  != Float64     #standard behavior for mismatched dims
 @test typeof(1.0u"m"/u"mm")  == Float64        #altered behavior
 @test 1.0u"m"/u"mm"  == 1000.0        #altered behavior
"""
function /{T, D, UA,  UU}(a::Unitful.Quantity{T,D,UA}, 
    u::Unitful.Units{UU,D})
    float(Unitful.convfact(u,UA()))    
end
```

**Comment by c42f** [comment]
Another more verbose design would be to enhance `ustrip` with the following two methods:

```julia
Unitful.ustrip(u::Unitful.Units, q::Unitful.Quantity) = ustrip(uconvert(u, q))
Unitful.ustrip(T::Type, u::Unitful.Units, q::Unitful.Quantity) = convert(T, ustrip(uconvert(u, q)))
```

This would be more explicit than your solution and less annoying than the current status quo:

```julia
println("The field intensity is $(ustrip(Float64, u"V/m", E)) [V/m] in a gap of $(ustrip(Float64, u"m", d) [m]")
```

Hah, the println example is probably not ideal, as units are already formatted very nicely in string interpolation ;-)

BTW, I feel it might even be better to deprecate `ustrip` as it currently exists. It almost inherently belongs together with `uconvert` and I'd argue that it's usually a bug to do `ustrip(x)` rather than `ustrip(uconvert(u, x))` in generic code.

@ajkeller34 what's your preferred approach? I feel this is *the* major cause of friction in using this library in day to day interactive work.

**Comment by cstjean** [comment]
+1. I've been using `Unitful.ustrip(u::Unitful.Units, q::Unitful.Quantity) = ustrip(uconvert(u, q))` in my code for the last several months, and I completely agree with @c42f; it's much safer than plain `ustrip(q)`

**Comment by c42f** [comment]
> it might even be better to deprecate ustrip as it currently exists

On the other hand, when *wrapping* functions from unit-unaware code, it's valid if `ustrip` is carefully combined with `unit`. For example:

https://github.com/ajkeller34/Unitful.jl/blob/050f893a02f0aa9017c8fcc487f4b63a5f6560bf/src/units.jl#L275

Of course, this could be more explicitly written as

```julia
Base.mul12(x::Quantity, y::Quantity) = Base.mul12(ustrip(unit(x), x), ustrip(unit(y), y)) .* (unit(x) * unit(y))
```

Regarding conversion to float as in the original proposal here - this would be really convenient. But I don't think we can have it without being inconsistent with the way conversions are handled in the rest of the package.

**Comment by c42f** [comment]
See #205

**Comment by cstjean** [comment]
@phlavenk I realized that you could implement the syntax you asked for with `getindex`:

```julia
julia> using Unitful

julia> using Unitful: m, mm

julia> x = 5m
5 m

julia> Base.getindex(q::Quantity, u::Unitful.Units) = ustrip(u, q)

julia> x[mm]
5000
```

I don't think it really belongs in this package, but it seems safe to use this definition in your code.
