### ISSUE TITLE
typo in deps/build.jl

### ISSUE THREAD

**Issue by KlausC** [ajkeller34/Unitful.jl#50]
`julia> typeof(u"ha")
Unitful.Units{(Unitful.Unit{:Are}(2,1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(1//1),)}}

julia> typeof(u"a")
Unitful.Units{(Unitful.Unit{:Are}(0,1//1),),Unitful.Dimensions{(Unitful.Dimension{:Length}(2//1),)}}
`
The dimension of should be L^2 in both cases, I guess.

`const ha = Unitful.Units{(Unitful.Unit{:Are}(2,1//1),), typeof(𝐋^2)}()`  deps/build.jl: 85

**Comment by ajkeller34** [comment]
Thanks, that's a typo. I'm preparing a new version of Unitful for julia 0.6 at the moment; I'll fix the typo in that branch.

**Comment by ajkeller34** [comment]
Fixed on master (see "latest" docs for info about the upcoming version 0.1.0).
