### ISSUE TITLE
Allow testing approx equality

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#64]
Currently get this error:

```
  Got an exception of type MethodError outside of a @test
  MethodError: no method matching eps(::Unitful.Quantity{Float64,Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)},Unitful.Units{(Unitful.Unit{:Gram,Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)}}(3,1//1),),Unitful.Dimensions{(Unitful.Dimension{:Mass}(1//1),)}}})
  Closest candidates are:
    eps(!Matched::Date) at dates/types.jl:231
    eps(!Matched::DateTime) at dates/types.jl:230
    eps() at float.jl:499
```

------

**edit**: something along the lines (but as a test macro):

```
function is_within_error(v_actual, v_approx, rel_error=1e-4)

  if v_actual == v_approx
    return true
  end

  if ( v_actual == typeof(v_actual)(0) )
    v_actual, v_approx = v_approx, v_actual
    # or return false or throw an error?
  end

  relative_error = abs( v_actual - v_approx ) / abs(v_actual)
  relative_error < rel_error

end
```

**Comment by ajkeller34** [comment]
Can you post the code you used to get the error? I assume you tried using `@test isapprox(...)` with quantities and encountered a problem, but without knowing exactly what you did I can't reproduce the issue.

**Comment by djsegal** [comment]
`@test isapprox(...)` worked perfectly

where in the docs is it?

**Comment by ajkeller34** [comment]
It's not in the docs—I haven't documented when I extend functions found in Base to work with quantities/units. I have only been documenting when I make new functions. Maybe I should start a list of the functions in Base that work with Unitful.
