### ISSUE TITLE
Add density to pkgdefaults.jl

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#65]
I'm trying to have a particle density (`#Particles/volume`).

I just noticed nothing like that was in:

+ [pkgdefaults.jl](https://github.com/ajkeller34/Unitful.jl/blob/2b72133313715ede189090a197e6abf6592bdebb/src/pkgdefaults.jl)

**Comment by ajkeller34** [comment]
Density is a bit ambiguous since it could refer also to per-area or per-length. Depending on exactly what you're doing, you can probably get pretty far without changing Unitful itself by using `@derived_dimension`.

**Comment by djsegal** [comment]
I ended up using this line:

```
Unitful.@unit n20 "n20" PlasmaDensity 1e20/Unitful.m^3 false
```

-------

How would you have written it?

**Comment by ajkeller34** [comment]
That works. I just meant that if you want to dispatch on quantities with the same dimension, you can do the following:

```
julia> Unitful.@unit n20 "n20" ParticleDensity20 1e20/Unitful.m^3 false
n20

julia> Unitful.@derived_dimension VolumeDensity Unitful.𝐋^-3

julia> isa(1.0n20, VolumeDensity)
true
```
