### ISSUE TITLE
Way to convert mass to Mev/c^2

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#67]
The docs don't specify a way to add a new conversion of this variety

**Comment by ajkeller34** [comment]
In the new release (v0.2.0), `c` is now a unit, to permit converting mass into `MeV/c^2`, for example. `c0` is still a quantity equal to the speed of light in vacuum, in units of `m/s`.

**Comment by djsegal** [comment]
Could you post an example syntax?

**Comment by ajkeller34** [comment]
Use either of:

```
julia> uconvert(u"meV/c^2", 1.0u"kg")
5.6095886500206866e38 c^-2 meV
```

```
julia> 1.0u"kg" |> u"meV/c^2"
5.6095886500206866e38 c^-2 meV
```

**Comment by ajkeller34** [comment]
(you may need to `Pkg.update()`)
