### ISSUE TITLE
Integration with JLD.jl

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#68]
Might be related to #9:

-----------

currently `write`ing Unitful variables to a JLD file causes the current error:

`ERROR: LoadError: LoadError: LoadError: type parameters with objects of type Tuple{Unitful.Dimension{:Length},Unitful.Dimension{:Mass},Unitful.Dimension{:Time}} are currently unsupported`

From  [JLD.jl/src/JLD.jl](https://github.com/JuliaIO/JLD.jl/blob/4dc944753ab983dd528a01c743f3e72d5f3b8331/src/JLD.jl#L1085-L1097), it looks like the following condition needs to be satisfied:

```
isbits(x) && parse(s) === x && !isa(x, Tuple)
```

**Comment by ajkeller34** [comment]
This is not a Unitful issue and there is already an issue raised at JLD (https://github.com/JuliaIO/JLD.jl/issues/128)

(Also, I would hesitate before saving Unitful variables to a JLD file—if the type signatures change, you wouldn't be able to load old data easily. Probably better just to implement your own saving/loading hook to save a `Float64` and some info you can use to reconstruct the Unitful variable later.)

**Comment by djsegal** [comment]
Related to this, how do you print `1u"keV"`:
+ as `1u"keV"` 
+ not `1 keV`?

**Comment by djsegal** [comment]
@ajkeller34,

Related to this, how do you print `1u"keV"`:
+ as `1u"keV"` 
+ not `1 keV`?
