### ISSUE TITLE
unexpected results of Unitful type hierarchy

### ISSUE THREAD

**Issue by deszoeke** [ajkeller34/Unitful.jl#69]
Unitful.jl is testament to the fact that physical units are superbly useful, even for computation. In fact, I assert that nondimensional numbers are _also_ superbly useful.

Typically I want to attach units to variables, so whatever units I start with, I can specify how to calculate things correctly with some set of mutually compatible units. Yet after converting inputs to the compatible units, I want the computer to do a nondimensional (often floating point) calculation. Now that there is Unitful, it can express the result in sensible and correct units too.

I would like to be able to dispatch functions specifically on nondimensional `Number`s. I don't know how to do this, perhaps because I'm just learning Julia types and methods. I can make methods that dispatch on whether I pass a function, e.g.,  a `::Pressure` or a `::Temperature`, but there's no type syntax I know of to dispatch a method to operate particularly on a NonDimensionalNumber. It seems awkward because `Quantity <: Number`, so that `Number` includes nondimensional `Numbers` and nondimensional and dimensional `Unitful.Quantity`s. My desired NonDimensionalNumber abstract type would include `Numbers` that are not `Quantity`s, or at least not dimensional ones. Whether variables have this property can be assessed at run time, but not when the compiler dispatches using type.

```
julia> Quantity <: Number
true

julia> DimensionlessQuantity <: Quantity
true

julia> isa(1u"m/m",DimensionlessQuantity)
false

julia> isa(1,DimensionlessQuantity)
false

julia> isa(1//1,DimensionlessQuantity)
false

julia> isa(NoUnits(1u"m/μm"),DimensionlessQuantity)
false
```

There are lots of physically meaningful nondimensional numbers: e.g. ratios of things with the same dimensions. Some nondimensional numbers even have hallowed names like Reynolds and Rayleigh. Scientific computation has made itself very useful dealing entirely with nondimensional numbers, or at any rate not knowing the numbers were dimensional, leaving pesky unit conversions to humans.

**Comment by ajkeller34** [comment]
Are you sure you actually need to dispatch on non-dimensional numbers? Can you provide an example? I'm not sure what you're trying to do but it sounds to me like you're trying to write method signatures which are overly specific.

One thing to keep in mind is that Julia is pretty good at eliding run-time checks where possible. Take the following:

```
julia> function dimensionless_add(x::Number, y::Number)
         dimension(x) != NoDims && error("$x not dimensionless")
         dimension(y) != NoDims && error("$y not dimensionless")
         x+y
       end
f (generic function with 1 method)
```

You'd think you'd pay some runtime penalty from the checks, right? Turns out this is not necessarily the case:
```
julia> @code_llvm dimensionless_add(1,2)

define i64 @julia_dimensionless_add_67097(i64, i64) #0 !dbg !5 {
top:
  %2 = add i64 %1, %0
  ret i64 %2
}
```
Notice how there is no error checking in the generated LLVM IR. (If you aren't familiar with LLVM IR, I'm not well versed either and not a good person to ask about it, but you can see pretty clearly that the method is just adding two numbers and returning the result.) This is probably because the function `dimension` can determine if a quantity has dimensions or not based on looking at the type alone. At no point did I write a method for `dimension` that needed to dispatch on a "nondimensional number" type. You can take a look in Unitful to see all the methods I defined for `dimension`.

P.S. The `DimensionlessQuantity` type is really what it says it is: any dimensionless `Quantity` type, not any numeric type which is dimensionless. It's used internally in Unitful but I'm not sure how useful it is in general.

**Comment by deszoeke** [comment]
That's a nice property of the julia compiler you point out. I suspect I am indeed ODing on overly specific methods.

In atmospheric thermodynamics I have functions for computing equilibrium phase transitions of water and adiabatic temperature and pressure changes for expansion of air. The functions are of a few variables, each of which may be specified in different units  (°C, K, Pa, hPa), making for a large number of combinations, and unit errors in calculations. Unitful does the conversions correctly when units are supplied for everything. For backward compatibility I also want to assume default units when they are not specified.

These typealiases seem to let me dispatch on the nondimensional property in method signatures. They may or may not result in shorter or clearer code than calling dimension() inside my function:
```
using Unitful
using Unitful: Pa, hPa, K, °C

typealias NondimensionalNumber Union{Real, Complex} # not including Quantities

# expects T in °C, p in hPa, uses Buck 1981 numerical constants
# converts to expected units, nondimensionalize, calculate
es(T::NondimensionalNumber,p::NondimensionalNumber) = 6.1121hPa*(1.0007 + 3.46e-8*p).*exp((17.502*T)./(240.97 + T))
es(T::Temperature,p::Pressure) = es(NoUnits(°C(T)/°C),NoUnits(p/hPa)) # resolves ambiguity below
# ...weird corner cases of mixed unitful and unitless quantities could be handled...
```

A nicer way to do this might be to make a specific method that expects `Unitful.Quantity` arguments, and a more general wrapper method that convert all arguments to `Unitful.Quantity`s before calling the specific method. Extending uconvert to unitize nondimensional numbers upon request would be useful for this:
```
import Unitful.uconvert
uconvert(a::Unitful.Units, x::NondimensionalNumber) = a*x

# specific method calculates
b(t::Temperature)=Unitful.σ*K(t)^4
# wrapper converts argument(s)
b(t::NondimensionalNumber)=b(uconvert(K, t))
```
Multiple arguments, dimensional and nondimensional, can be converted by the wrapper.

Thanks again for the great package.

**Comment by ajkeller34** [comment]
I suspect the latter approach will lead to clearer code. Although, I wouldn't define a new method for `Unitful.uconvert`, which might lead to some unexpected behavior. Instead, consider:

```
b(t::Temperature)=Unitful.σ*(uconvert(u"K", t))^4
b(::Quantity) = error("not a temperature")
b(t::Number) = b(t*u"K")
```

In this way, there is a fallback to try and construct a temperature from a generic `Number` type, even if it is not `Real` or `Complex`. The only way this should fail is if for instance you tried to combine Unitful with another package that implements dimensionful quantities, which seems like a recipe for a bad time.

Actually, you shouldn't even need the `uconvert(u"K",t)` in the first definition, but it seems like raising 0ºC to a power does not convert to an absolute scale first, leading to incorrect answers. I consider this a bug (https://github.com/ajkeller34/Unitful.jl/issues/72) and can fix this in the next release.

Glad you like the package.

**Comment by deszoeke** [comment]
I see I am making the `uconvert(a,x::Number)` method less strict and less safe. I'll use `myuconvert` that shadows `uconvert`.
```
myuconvert(args...)=uconvert(args...)
myuconvert(a::Unitful.Units, x::NondimensionalNumber) = a*x
```
Considering there are 2^(N=number of arguments of indeterminate dimensions) methods on which one has to dispatch--or 3^N to catch arguments of the wrong dimensions--doing all the unit conversions in a single general wrapper call is preferable. Without nice error catching, the 2-argument function needs 4 methods:
```
theta(T::Temperature,p::Pressure) = K(T)/NoUnits(p/(1000*u"hPa"))^(2//7)
#unit-conditioning wrappers follow
theta(T::NondimensionalNumber, p::Pressure)=theta(T*u"K",p)
theta(T::Temperature, p::NondimensionalNumber)=theta(T,p*u"hPa")
theta(T::NondimensionalNumber, p::NondimensionalNumber)=theta(T*u"K", p*u"hPa")
```
while the single unit-conditioning wrapper takes the place of 3 of these
```
theta(T::Number, p::Number)=theta(myuconvert(u"K",T), myuconvert(u"hPa",p))
```

There may be a way around it, but I was having method ambiguities using just `::Number` type assertions with multiple arguments in the first approach. Anyway, the point of the example is there are quickly too many methods to write in the first approach, let alone to comb for method ambiguities. I'm not sure about the compiled efficiency.

Thanks for your suggestions. I am well on my way to making useful and good unit-aware functions.
