### ISSUE TITLE
Method for exp with DimensionlessQuantity

### ISSUE THREAD

**Issue by giordano** [ajkeller34/Unitful.jl#70]
Is there a particular reason why there is no method for `exp` with `DimensionlessQuantity` argument?

**Comment by ajkeller34** [comment]
Good catch. Probably because it doesn't make sense for dimensionful quantities, I didn't implement it for dimensionless ones. If you make a PR with a test, I'll merge it, otherwise I'll do it in the next update.

**Comment by giordano** [comment]
> Good catch. Probably because it doesn't make sense for dimensionful quantities, I didn't implement it for dimensionless ones.

I completely agree, but unless division between homogeneous quantities automatically gives a pure number (something suggested in #48), I think this package should provide `DimensionlessQuantity` methods for such functions.

Since there are methods for logarithm-related functions, I was surprised not to see a more ubiquitous function supported ;-)

> If you make a PR with a test, I'll merge it, otherwise I'll do it in the next update.

I think I can do that, thanks.
