### ISSUE TITLE
Method to collapse/squash/simplify units

### ISSUE THREAD

**Issue by djsegal** [ajkeller34/Unitful.jl#73]
As mentioned in #13 and a few other issues, there is currently no way to squash:

+ something like `7 MeV/keV`
+ to `7e+3 (dimensionless)`

Can you add a `simplify(unitful_variable)` method (or something like that) to handle this?

Even if it wasn't robust or kind of wonky at first, I think it still gives a good addition moving forward

**Comment by ajkeller34** [comment]
`7u"MeV/keV" |> NoUnits`
