### ISSUE TITLE
Behaviour of floating point range inconsistent with Julia 0.5

### ISSUE THREAD

**Issue by mdavezac** [ajkeller34/Unitful.jl#77]
When doing a range with floats in Julia:

~~~Julia
julia> 1:1:4.1
1.0:1.0:4.0
~~~

The end is adjusted and step is kept constant.

However, with Unitful values, the opposite is true:

~~~Julia
julia> 1u"m":1u"m":4.1u"m"
4-element Ranges.LinSpace{Quantity{Float64, Dimensions:{𝐋}, Units:{m}}}:
 1.0 m,2.03333 m,3.06667 m,4.1 m
~~~

I'm not sure whether this is bug or a feature....

**Comment by ajkeller34** [comment]
This is no longer an issue on 0.6 (the same start, step, and stop is returned even with the meter units). For 0.5, the Ranges.jl package is used to try to support unitful ranges, owing to shortcomings in Base. Currently this means returning a `LinSpace`. The amount of effort that goes into getting ranges to work intuitively is significant, so I'm not sure how best to fix it and satisfy everyone. The obvious answer is to prepare for 0.6, which should be ready pretty soon, presumably.

**Comment by timholy** [comment]
Hmm, I hadn't even noticed this. Sorry about that.

Really what I should do is backport all those range changes to Compat. It just seems like a big job, and that's been a disincentive. Still, this issue is more incentive.

**Comment by mdavezac** [comment]
Personally, I'm happy to wait for 0.6. It's just part of the fun of working with <v1.0!
Until then, I can adjust the end points to always hit the right value square on.

**Comment by ajkeller34** [comment]
Now that Julia 0.6 is out and Unitful 0.3.0 requires it, I'm going to mark this as closed.
