### ISSUE TITLE
Behavior of `floor`, `ceil` is surprising

### ISSUE THREAD

**Issue by ajkeller34** [ajkeller34/Unitful.jl#78]
`floor` and `ceil` pretend the units aren't there. Not sure why I did it this way, but I think this warrants reconsideration:

```
julia> 20u"µm"/(110u"nm")
0.18181818181818182 nm^-1 μm

julia> floor(ans)
0.0 nm^-1 µm

julia> Int(ans)
0
```

... which is different from the expected answer of 181. My inclination is to define `floor` and `ceil` only for dimensionless quantities and have them convert to a unitless number first.

**Comment by giordano** [comment]
Also `isinteger` really depends on the actual units and can give unexpected result for non simplified quantities:
```julia
julia> isinteger(1u"m" / 10u"mm")
false

julia> isinteger(uconvert(NoUnits, 1u"m" / 10u"mm"))
true
```

**Comment by ajkeller34** [comment]
`trunc` and `round` also had the same problems, but I think the latest patch should fix these issues.
