### ISSUE TITLE
Julia Julia Version 0.5.0-dev+3192 requires Core.Intrinsics?

### ISSUE THREAD

**Issue by goedman** [ajkeller34/Unitful.jl#8]
Hi Andrew,

I noticed that with this mornings build of Julia 0.5.0- Intrinsics.box on lines 54 and 55 of Unitful.jl needed to be replaced by Core.Intrinsics.box.

As I have added some oil field units it's a bit tricky to generate a PR, but if that would help I can do it.

Thanks for a great Pkg!

Rob

**Comment by ajkeller34** [comment]
I’m glad you’re making use of the package. Sounds like a pretty simple fix, so I can take care of that soon. Thanks for the heads up!

I’m trying to resolve some of the warnings that occur upon package load, but these will require changes to Julia base, so progress is slow...

Best,
Andrew

**Comment by goedman** [comment]
Thanks Andrew,

Indeed I noticed this morning that it was fixed and I realize that the warnings on startup will take longer to get fixed. 

It does not  prevent me from using the package as at the moment I primarily use Unitful to initially convert an input dictionary to an SI units based dictionary and at the end of the (finite element) calculations I convert a few DataFrames to the units of the input dictionary.

Regards,
Rob
