### ISSUE TITLE
ERROR: type Float64 has no field val

### ISSUE THREAD

**Issue by timholy** [ajkeller34/Unitful.jl#85]
Here's a strange error (0.6.0-rc2) that I don't fully understand:
```julia
julia> using Unitful

julia> r = linspace(1,5,7)
1.0:0.6666666666666666:5.0

julia> s = u"s"
s

julia> x = 1.0s
1.0 s

julia> r*x
ERROR: type Float64 has no field val
Stacktrace:
 [1] _mul2 at ./twiceprecision.jl:484 [inlined]
 [2] *(::Base.TwicePrecision{Float64}, ::Quantity{Float64, Dimensions:{𝐓}, Units:{s}}) at ./twiceprecision.jl:488
 [3] *(::StepRangeLen{Float64,Base.TwicePrecision{Float64},Base.TwicePrecision{Float64}}, ::Quantity{Float64, Dimensions:{𝐓}, Units:{s}}) at ./range.jl:747
```

But now launch julia as `julia --inline=no`, and it works fine.

I suspect this is a codegen bug, but before I report it...do you have any insight?

**Comment by ajkeller34** [comment]
This seems like a codegen bug to me as well. Looking at the definition of the method from stacktrace [2]:

```
function *(x::TwicePrecision{R}, v::S) where R where S<:Number
    T = promote_type(R, S)
    _mul2(convert(TwicePrecision{T}, x), convert(T, v))
end
```

Using 0.6.0-rc2 on OS X, if I use `@which` to see what method of `_mul2` is called, it is:

```
julia> T = promote_type(Float64, typeof(1.0u"s"))
Unitful.Quantity{Float64,D,U} where U where D

julia> @which Base._mul2(convert(Base.TwicePrecision{T}, 1.0), convert(T, 1.0u"s"))
_mul2(x::Base.TwicePrecision, v::Number) in Base at twiceprecision.jl:484
```

Calling `_mul2` returns an error but running the code in the body of that method does not:

```
julia> Base._mul2(convert(Base.TwicePrecision{T}, 1.0), convert(T, 1.0u"s"))
ERROR: type Float64 has no field val
Stacktrace:
 [1] _mul2(::Base.TwicePrecision{Unitful.Quantity{Float64,D,U} where U where D}, ::Quantity{Float64, Dimensions:{𝐓}, Units:{s}}) at ./twiceprecision.jl:484

julia> Base.TwicePrecision(convert(Base.TwicePrecision{T}, 1.0).hi*1.0u"s", convert(Base.TwicePrecision{T}, 1.0).lo*1.0u"s")
Base.TwicePrecision{Quantity{Float64, Dimensions:{𝐓}, Units:{s}}}(1.0 s, 0.0 s)
```

There are some silly things in promotion happening in Unitful (including #52 as you are aware) but I fail to see how that could be responsible. 

By the way, while I have your attention, do you have any thoughts on https://github.com/ajkeller34/Unitful.jl/issues/79 or the associated PR? It is an important problem but I am hesitant to use BigNums... maybe I don't have a choice. I suspect you may have more experience in thinking about these kinds of problems than I do, so I thought I would ask.

**Comment by timholy** [comment]
> By the way, while I have your attention, do you have any thoughts on #79 or the associated PR? It is an important problem but I am hesitant to use BigNums... maybe I don't have a choice. I suspect you may have more experience in thinking about these kinds of problems than I do, so I thought I would ask.

Can you get away with `Int128` for these conversions? If so, that would probably be a nicer answer---the performance is orders of magnitude higher. If `Int128` is too small but `Int256` would be OK, you can "fake" it with `Base.TwicePrecision{UInt128}` though you'll probably have to define the arithmetic operations for that type (TwicePrecision was created with AbstractFloats in mind). The general strategy is "splitting" and then using the distributive rule:
```julia
"""
    hi, lo = split(x)

Split the `hi` and `low` bits of `x` into two equal pieces. Both have the same type as `x`, but all the high bits are 0.
"""
split(x::UInt128) = x >> 64, x & (typemax(UInt128)>>64)
```
And then since `x = hi * (UInt128(1)<<64) + lo`, you can implement `x*y` using the distributive rule, with the key point being that because `hi` and `lo` are "padded" with 64 zero bits, you can be certain that `x.hi*y.hi` will not overflow. For signed numbers it's probably best to pull out the sign separately and do all computations using `Unsigned` integers.

**Comment by ajkeller34** [comment]
Thank you for the PR and your thoughtful suggestions. I'll try to implement this when I get a free moment / emerge from the clean room...
