### ISSUE TITLE
Operator method for DataArrays NAType * Units

### ISSUE THREAD

**Issue by Crghilardi** [ajkeller34/Unitful.jl#91]
While working through various scenarios, I found that the NA values from DataArrays does not accept the bare unit syntax available to other types. Would there be any interest in adding this to the * operator overload in Unitful.jl for consistency?

```
using DataArrays
A=DataArray([1, 2, 3, 4 ,5], [true, false, true,false, true])

A.*u"cm" #throws method error
A.*1u"cm" #but this works 
A.*1.0u"cm" #and this

import Base.*
 *(x::DataArrays.NAtype,y::Unitful.Units) = x  #just return NAType like with Ints and Floats

A.*u"cm" #now this syntax works as well
```

**Comment by ajkeller34** [comment]
To write such a method in Unitful I'd have to add DataArrays as a requirement, so I'd prefer not to do that (at least until conditional requirements are implemented well in Julia). If that's the only method you need, you should continue to define the method in your own code. An alternative would be to make/publish a UnitfulDataArrays package that requires both Unitful and DataArrays that collects the necessary methods for compatibility, but that seems like overkill for one method.
