### ISSUE TITLE
Need better accounting of where units are defined

### ISSUE THREAD

**Issue by mweastwood** [ajkeller34/Unitful.jl#94]
Consider this example:

```julia
julia> using Unitful

julia> module UnitfulTest 
           import Unitful
           using Unitful: @unit, s
           @unit twoseconds "twoseconds" TwoSeconds 2s false
           Unitful.register(UnitfulTest)
       end
UnitfulTest

julia> uconvert(u"s", 1*u"twoseconds")
WARNING: Symbol s was found in multiple registered unit modules. We will use the one from UnitfulTest.
2//1 s
```

At the moment it is impossible to import units into a module that is later registered with Unitful. This generates a warning because Unitful thinks the unit is defined twice.

I think the `@unit` macro should push to a module-local list that keeps track of which units are defined in that module. Then you no longer need to use `isdefined(module, symbol)` to locate where units are defined.

**Comment by ajkeller34** [comment]
Closed by #98.
