### ISSUE TITLE
Inexact conversion

### ISSUE THREAD

**Issue by devmotion** [ajkeller34/Unitful.jl#95]
Hi!

I just discovered the following strange behaviour when converting simple units:
```julia
julia> convert(typeof(1.0u"N"), 1e-3u"mN")
1.0e-6 N

julia> 1.0e-6u"N" == convert(typeof(1.0u"N"), 1e-3u"mN")
true

julia> convert(typeof(1.0u"N"), 1e-4u"mN")
1.0000000000000001e-7 N

julia> 1.0e-7u"N" == convert(typeof(1.0u"N"), 1e-4u"mN")
false

julia> convert(typeof(1.0u"N"), 1e-5u"mN")
1.0e-8 N

julia> 1.0e-8u"N" == convert(typeof(1.0u"N"), 1e-5u"mN")
true
```
I tested all other exponents with absolute value less or equal than 20, and the inexact conversion happens also for exponents -8, -9, -13, -17, and -18.

**Comment by ajkeller34** [comment]
If I have `1e-4u"mN"` and I want to convert to `N`, I should divide by 1000, so:
```
julia> 1e-4/1000
1.0000000000000001e-7
```

On the other hand:
```
julia> 1e-3/1000
1.0e-6
```

What you observe seems to be a quirk of `Float64`, so I'm not sure I can address this.
